# to see all the Rules from SwiftLint checkout this link
# https://github.com/realm/SwiftLint/blob/master/Rules.md


disabled_rules:
- trailing_whitespace
- large_tuple

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

identifier_name:
  allowed_symbols: "_"
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1

line_length:
    warning: 175
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 600

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 25
    error: 35

reporter: "xcode"
